export const ONE_SECOND = 1;
export const ONE_MINUTE_IN_SECONDS = ONE_SECOND * 60;
export const ONE_HOUR_IN_SECONDS = ONE_MINUTE_IN_SECONDS * 60;
export const ONE_DAY_IN_SECONDS = ONE_HOUR_IN_SECONDS * 24;
